apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2   # 🔥 auto-scaling base
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: ai-backend:latest
          ports:
            - containerPort: 8000